// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAXZhhfBTbmCQsO6jAU07BMOKLy3CsK8c',
    appId: '1:769267702281:web:29b3d272ae262d80ea76d8',
    messagingSenderId: '769267702281',
    projectId: 'my-portfolio-b2442',
    authDomain: 'my-portfolio-b2442.firebaseapp.com',
    storageBucket: 'my-portfolio-b2442.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaQwR8NsXkYjVVNmtoTviuIIpwpRudg6M',
    appId: '1:769267702281:android:f229432874535fddea76d8',
    messagingSenderId: '769267702281',
    projectId: 'my-portfolio-b2442',
    storageBucket: 'my-portfolio-b2442.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARSDC81pYL1G60zi9DJJ9307T-FRojjOw',
    appId: '1:769267702281:ios:5bc6306418157252ea76d8',
    messagingSenderId: '769267702281',
    projectId: 'my-portfolio-b2442',
    storageBucket: 'my-portfolio-b2442.firebasestorage.app',
    iosBundleId: 'com.flutter.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARSDC81pYL1G60zi9DJJ9307T-FRojjOw',
    appId: '1:769267702281:ios:94e95a6c0812c2f6ea76d8',
    messagingSenderId: '769267702281',
    projectId: 'my-portfolio-b2442',
    storageBucket: 'my-portfolio-b2442.firebasestorage.app',
    iosBundleId: 'com.example.portfolioWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAXZhhfBTbmCQsO6jAU07BMOKLy3CsK8c',
    appId: '1:769267702281:web:ce02e71a85d7e239ea76d8',
    messagingSenderId: '769267702281',
    projectId: 'my-portfolio-b2442',
    authDomain: 'my-portfolio-b2442.firebaseapp.com',
    storageBucket: 'my-portfolio-b2442.firebasestorage.app',
  );
}
